-- Small config file with info like weapon name -> weapon, vehicles, and peds list


config = {}

config.weapons = {

    melee = {

        ['Knife']                   = 'weapon_knife',
        ['Knuckle']                 = 'weapon_knuckle',
        ['Nightstick']              = 'weapon_nightstick',
        ['Hammer']                  = 'weapon_hammer',
        ['Bat']                     = 'weapon_bat',
        ['Golfclub']                = 'weapon_golfclub',
        ['Crowbar']                 = 'weapon_crowbar',
        ['Bottle']                  = 'weapon_bottle',
        ['Dagger']                  = 'weapon_dagger',
        ['Hatchet']                 = 'weapon_hatchet',
        ['Machete']                 = 'weapon_machete',
        ['Flashlight']              = 'weapon_flashlight',
        ['Switchblade']             = 'weapon_switchblade',
        ['Pool Cue']                = 'weapon_poolcue',
        ['Pipe Wrench']             = 'weapon_pipewrench',
        ['Stone Hatchet']           = 'weapon_stone_hatchet',
        ['Battle Axe']              = 'weapon_battleaxe'   

    },      

    handguns = {     

        ['Pistol']                  = 'weapon_pistol',
        ['Combat Pistol']           = 'weapon_combatpistol',
        ['Revolver']                = 'weapon_revolver',
        ['Ap Pistol']               = 'weapon_appistol',
        ['Pistol 50']               = 'weapon_pistol50',
        ['Sns Pistol']              = 'weapon_snspistol',
        ['Heavy Pistol']            = 'weapon_heavypistol',
        ['Vintage Pistol']          = 'weapon_vintagepistol',
        ['Stun Gun']                = 'weapon_stungun',
        ['Flare Gun']               = 'weapon_flaregun',
        ['Marksman Pistol']         = 'weapon_marksmanpistol',
        ['Pistol Mk2']              = 'weapon_pistol_mk2',
        ['Sns Pistol Mk2']          = 'weapon_snspistol_mk2',
        ['Revolver Mk2']            = 'weapon_revolver_mk2',
        ['Double Action']           = 'weapon_doubleaction',
        ['Navy Revolver']           = 'weapon_navyrevolver',
        ['Ceramic Pistol']          = 'weapon_ceramicpistol',
        ['Ray Pistol']              = 'weapon_raypistol',
        ['Perico Pistol']           = 'weapon_gadgetpistol'

    },      

    submachineguns = {     

        ['Micro Smg']               = 'weapon_microsmg',
        ['Mini Smg']                = 'weapon_minismg',
        ['Machine Pistol']          = 'weapon_machinepistol',
        ['Smg']                     = 'weapon_smg',
        ['Assault Smg']             = 'weapon_assaultsmg',
        ['Combat Pdw']              = 'weapon_combatpdw',
        ['Smg Mk2']                 = 'weapon_smg_mk2',
        ['Ray Carbine']             = 'weapon_raycarbine'

    },      

    shotguns = {        

        ['Pump Shotgun']            = 'weapon_pumpshotgun',
        ['Sweeper Shotgun']         = 'weapon_autoshotgun',
        ['Sawnoff Shotgun']         = 'weapon_sawnoffshotgun',
        ['Bullpup Shotgun']         = 'weapon_bullpupshotgun',
        ['Assault Shotgun']         = 'weapon_assaultshotgun',
        ['Heavy Shotgun']           = 'weapon_heavyshotgun',
        ['Double Barrel Shotgun']   = 'weapon_dbshotgun',
        ['Pumpshotgun Mk2']         = 'weapon_pumpshotgun_mk2',
        ['Musket']                  = 'weapon_musket',
        ['Combat Shotgun']          = 'weapon_combatshotgun'

    },  

    assaultrifles = {   

        ['Assault Rifle']           = 'weapon_assaultrifle',
        ['Assaultrifle Mk2']        = 'weapon_assaultrifle_mk2',
        ['Carbine Rifle']           = 'weapon_carbinerifle',
        ['Carbinerifle Mk2']        = 'weapon_carbinerifle_mk2',
        ['Advanced Rifle']          = 'weapon_advancedrifle',
        ['Special Carbine']         = 'weapon_specialcarbine',
        ['Bullpup Rifle']           = 'weapon_bullpuprifle',
        ['Compact Rifle']           = 'weapon_compactrifle',
        ['Military Rifle']          = 'weapon_militaryrifle',
        ['Special Carbine Mk2']     = 'weapon_specialcarbine_mk2',
        ['Bullpuprifle Mk2']        = 'weapon_bullpuprifle_mk2'

    },  

    lightmachineguns = {    

        ['MG']                      = 'weapon_mg',
        ['Combat Mg']               = 'weapon_combatmg',
        ['Combatmg Mk2']            = 'weapon_combatmg_mk2',
        ['Gusenberg']               = 'weapon_gusenberg'

    },  

    sniperrifles = {    

        ['Sniper Rifle']            = 'weapon_sniperrifle',
        ['Heavy Sniper']            = 'weapon_heavysniper',
        ['Heavy Sniper Mk2']        = 'weapon_heavysniper_mk2',
        ['Marksman Rifle']          = 'weapon_marksmanrifle',
        ['Marksman Rifle Mk2']      = 'weapon_marksmanrifle_mk2'

    },

    heavyweapons = {

        ['Grenade Launcher']        = 'weapon_grenadelauncher',
        ['Grenade Launcher Smoke']  = 'weapon_grenadelauncher_smoke',
        ['RPG']                     = 'weapon_rpg',
        ['Minigun']                 = 'weapon_minigun',
        ['Firework Launcher']       = 'weapon_firework',
        ['Railgun']                 = 'weapon_railgun',
        ['Homing Launcher']         = 'weapon_hominglauncher',
        ['Compact Grenade']         = 'weapon_compactlauncher',
        ['Widowmaker']              = 'weapon_rayminigun'

    },

    throwables = {

        ['Proximity Mines']         = 'weapon_proxmine',
        ['BZ Gas']                  = 'weapon_bzgas',
        ['Tear Gas']                = 'weapon_smokegrenade',
        ['Molotov']                 = 'weapon_molotov',
        ['Snowballs']               = 'weapon_snowball',
        ['flare']                   = 'weapon_flare',
        ['Baseball']                = 'weapon_ball',
        ['Grenade']                 = 'weapon_grenade',
        ['Sticky Bomb']             = 'weapon_stickybomb',
        ['Pipe Bombs']              = 'weapon_pipebomb'

    },

    miscellaneous = {

        ['Fire extinguisher']       = 'weapon_fireextinguisher',
        ['Jerry Can']               = 'weapon_petrolcan',
        ['Hazardous Jerry Can']     = 'weapon_hazardcan',
        ['Parachute']               = 'gadget_parachute',
        ['Digiscanner']             = 'weapon_digiscanner'

    }
}


config.vehicles = {
    Compacts = {
        ['Asbo'] = 'asbo',
        ['Blista'] = 'blista',
        ['Brioso'] = 'brioso',
        ['Club'] = 'club',
        ['Dilettante'] = 'dilettante',
        ['Dilettante2'] = 'dilettante2',
        ['Kanjo'] = 'kanjo',
        ['Issi2'] = 'issi2',
        ['Issi3'] = 'issi3',
        ['Issi4'] = 'issi4',
        ['Issi5'] = 'issi5',
        ['Issi6'] = 'issi6',
        ['Panto'] = 'panto',
        ['Prairie'] = 'prairie',
        ['Rhapsody'] = 'rhapsody',
        ['Brioso2'] = 'brioso2',
        ['Weevil'] = 'weevil'  
    },
    Sedans = {
        ['Asea'] = 'asea',
        ['Asea2'] = 'asea2',
        ['Asterope'] = 'asterope',
        ['Cog55'] = 'cog55',
        ['Cog552'] = 'cog552',
        ['Cognoscenti'] = 'cognoscenti',
        ['Cognoscenti2'] = 'cognoscenti2',
        ['Emperor'] = 'emperor',
        ['Emperor2'] = 'emperor2',
        ['Emperor3'] = 'emperor3',
        ['Fugitive'] = 'fugitive',
        ['Glendale'] = 'glendale',
        ['Glendale2'] = 'glendale2',
        ['Ingot'] = 'ingot',
        ['Intruder'] = 'intruder',
        ['Limo2'] = 'limo2',
        ['Premier'] = 'premier',
        ['Primo'] = 'primo',
        ['Primo2'] = 'primo2',
        ['Regina'] = 'regina',
        ['Romero'] = 'romero',
        ['Stafford'] = 'stafford',
        ['Stanier'] = 'stanier',
        ['Stratum'] = 'stratum',
        ['Stretch'] = 'stretch',
        ['Superd'] = 'superd',
        ['Surge'] = 'surge',
        ['Tailgater'] = 'tailgater',
        ['Warrener'] = 'warrener',
        ['Washington'] = 'washington'        
    },
    Suvs = {
        ['Baller'] = 'baller',
        ['Baller2'] = 'baller2',
        ['Baller3'] = 'baller3',
        ['Baller4'] = 'baller4',
        ['Baller5'] = 'baller5',
        ['Baller6'] = 'baller6',
        ['Bjxl'] = 'bjxl',
        ['Cavalcade'] = 'cavalcade',
        ['Cavalcade2'] = 'cavalcade2',
        ['Contender'] = 'contender',
        ['Dubsta'] = 'dubsta',
        ['Dubsta2'] = 'dubsta2',
        ['Fq2'] = 'fq2',
        ['Granger'] = 'granger',
        ['Gresley'] = 'gresley',
        ['Habanero'] = 'habanero',
        ['Huntley'] = 'huntley',
        ['Landstalker'] = 'landstalker',
        ['Landstalker2'] = 'landstalker2',
        ['Mesa'] = 'mesa',
        ['Mesa2'] = 'mesa2',
        ['Novak'] = 'novak',
        ['Patriot'] = 'patriot',
        ['Patriot2'] = 'patriot2',
        ['Radi'] = 'radi',
        ['Rebla'] = 'rebla',
        ['Rocoto'] = 'rocoto',
        ['Seminole'] = 'seminole',
        ['Seminole2'] = 'seminole2',
        ['Serrano'] = 'serrano',
        ['Toros'] = 'toros',
        ['Xls'] = 'xls',
        ['Xls2'] = 'xls2',
        ['Squaddie'] = 'squaddie'        
    },
    Coupes = {
        ['Cogcabrio'] = 'cogcabrio',
        ['Exemplar'] = 'exemplar',
        ['F620'] = 'f620',
        ['Felon2'] = 'felon2',
        ['Jackal'] = 'jackal',
        ['Oracle'] = 'oracle',
        ['Oracle2'] = 'oracle2',
        ['Sentinel'] = 'sentinel',
        ['Sentinel2'] = 'sentinel2',
        ['Zion'] = 'zion',
        ['Zion2'] = 'zion2'        
    },
    Muscle = {
        ['Blade'] = 'blade',
        ['Buccaneer'] = 'buccaneer',
        ['Buccaneer2'] = 'buccaneer2',
        ['Chino'] = 'chino',
        ['Chino2'] = 'chino2',
        ['Clique'] = 'clique',
        ['Coquette3'] = 'coquette3',
        ['Deviant'] = 'deviant',
        ['Dominator'] = 'dominator',
        ['Dominator2'] = 'dominator2',
        ['Dominator3'] = 'dominator3',
        ['Dominator4'] = 'dominator4',
        ['Dominator5'] = 'dominator5',
        ['Dominator6'] = 'dominator6',
        ['Dukes'] = 'dukes',
        ['Dukes2'] = 'dukes2',
        ['Dukes3'] = 'dukes3',
        ['Faction'] = 'faction',
        ['Faction2'] = 'faction2',
        ['Faction3'] = 'faction3',
        ['Ellie'] = 'ellie',
        ['Gauntlet'] = 'gauntlet',
        ['Gauntlet2'] = 'gauntlet2',
        ['Gauntlet3'] = 'gauntlet3',
        ['Gauntlet4'] = 'gauntlet4',
        ['Gauntlet5'] = 'gauntlet5',
        ['Hermes'] = 'hermes',
        ['Hotknife'] = 'hotknife',
        ['Hustler'] = 'hustler',
        ['Impaler'] = 'impaler',
        ['Impaler2'] = 'impaler2',
        ['Impaler3'] = 'impaler3',
        ['Impaler4'] = 'impaler4',
        ['Imperator'] = 'imperator',
        ['Imperator2'] = 'imperator2',
        ['Imperator3'] = 'imperator3',
        ['Lurcher'] = 'lurcher',
        ['Moonbeam'] = 'moonbeam',
        ['Moonbeam2'] = 'moonbeam2',
        ['Nightshade'] = 'nightshade',
        ['Peyote2'] = 'peyote2',
        ['Phoenix'] = 'phoenix',
        ['Picador'] = 'picador',
        ['Ratloader'] = 'ratloader',
        ['Ratloader2'] = 'ratloader2',
        ['Ruiner'] = 'ruiner',
        ['Ruiner2'] = 'ruiner2',
        ['Ruiner3'] = 'ruiner3',
        ['Sabregt'] = 'sabregt',
        ['Sabregt2'] = 'sabregt2',
        ['Slamvan'] = 'slamvan',
        ['Slamvan2'] = 'slamvan2',
        ['Slamvan3'] = 'slamvan3',
        ['Slamvan4'] = 'slamvan4',
        ['Slamvan5'] = 'slamvan5',
        ['Slamvan6'] = 'slamvan6',
        ['Stalion'] = 'stalion',
        ['Stalion2'] = 'stalion2',
        ['Tampa'] = 'tampa',
        ['Tampa3'] = 'tampa3',
        ['Tulip'] = 'tulip',
        ['Vamos'] = 'vamos',
        ['Vigero'] = 'vigero',
        ['Virgo'] = 'virgo',
        ['Virgo2'] = 'virgo2',
        ['Virgo3'] = 'virgo3',
        ['Voodoo'] = 'voodoo',
        ['Voodoo2'] = 'voodoo2',
        ['Yosemite'] = 'yosemite',
        ['Yosemite2'] = 'yosemite2',
        ['Yosemite3'] = 'yosemite3'
    },
    Sport_Classics = {
        ['Ardent'] = 'ardent',
        ['Btype'] = 'btype',
        ['Btype2'] = 'btype2',
        ['Btype3'] = 'btype3',
        ['Casco'] = 'casco',
        ['Cheetah2'] = 'cheetah2',
        ['Coquette2'] = 'coquette2',
        ['Deluxo'] = 'deluxo',
        ['Dynasty'] = 'dynasty',
        ['Fagaloa'] = 'fagaloa',
        ['Feltzer3'] = 'feltzer3',
        ['Gt500'] = 'gt500',
        ['Infernus2'] = 'infernus2',
        ['Jb700'] = 'jb700',
        ['Jb7002'] = 'jb7002',
        ['Mamba'] = 'mamba',
        ['Manana'] = 'manana',
        ['Manana2'] = 'manana2',
        ['Michelli'] = 'michelli',
        ['Monroe'] = 'monroe',
        ['Nebula'] = 'nebula',
        ['Peyote'] = 'peyote',
        ['Peyote3'] = 'peyote3',
        ['Pigalle'] = 'pigalle',
        ['Rapidgt3'] = 'rapidgt3',
        ['Retinue'] = 'retinue',
        ['Retinue2'] = 'retinue2',
        ['Savestra'] = 'savestra',
        ['Stinger'] = 'stinger',
        ['Stingergt'] = 'stingergt',
        ['Stromberg'] = 'stromberg',
        ['Swinger'] = 'swinger',
        ['Torero'] = 'torero',
        ['Tornado'] = 'tornado',
        ['Tornado2'] = 'tornado2',
        ['Tornado3'] = 'tornado3',
        ['Tornado4'] = 'tornado4',
        ['Tornado5'] = 'tornado5',
        ['Tornado6'] = 'tornado6',
        ['Turismo2'] = 'turismo2',
        ['Viseris'] = 'viseris',
        ['Z190'] = 'z190',
        ['Ztype'] = 'ztype',
        ['Zion3'] = 'zion3',
        ['Cheburek'] = 'cheburek',
        ['Toreador'] = 'toreador'
    },
    Sports = {
        ['Alpha'] = 'alpha',
        ['Banshee'] = 'banshee',
        ['Bestiagts'] = 'bestiagts',
        ['Blista2'] = 'blista2',
        ['Blista3'] = 'blista3',
        ['Buffalo'] = 'buffalo',
        ['Buffalo2'] = 'buffalo2',
        ['Buffalo3'] = 'buffalo3',
        ['Carbonizzare'] = 'carbonizzare',
        ['Comet2'] = 'comet2',
        ['Comet3'] = 'comet3',
        ['Comet4'] = 'comet4',
        ['Comet5'] = 'comet5',
        ['Coquette'] = 'coquette',
        ['Coquette4'] = 'coquette4',
        ['Drafter'] = 'drafter',
        ['Deveste'] = 'deveste',
        ['Elegy'] = 'elegy',
        ['Elegy2'] = 'elegy2',
        ['Feltzer2'] = 'feltzer2',
        ['Flashgt'] = 'flashgt',
        ['Furoregt'] = 'furoregt',
        ['Fusilade'] = 'fusilade',
        ['Futo'] = 'futo',
        ['Gb200'] = 'gb200',
        ['Hotring'] = 'hotring',
        ['Komoda'] = 'komoda',
        ['Imorgon'] = 'imorgon',
        ['Issi7'] = 'issi7',
        ['Italigto'] = 'italigto',
        ['Jugular'] = 'jugular',
        ['Jester'] = 'jester',
        ['Jester2'] = 'jester2',
        ['Jester3'] = 'jester3',
        ['Khamelion'] = 'khamelion',
        ['Kuruma'] = 'kuruma',
        ['Kuruma2'] = 'kuruma2',
        ['Locust'] = 'locust',
        ['Lynx'] = 'lynx',
        ['Massacro'] = 'massacro',
        ['Massacro2'] = 'massacro2',
        ['Neo'] = 'neo',
        ['Neon'] = 'neon',
        ['Ninef'] = 'ninef',
        ['Ninef2'] = 'ninef2',
        ['Omnis'] = 'omnis',
        ['Paragon'] = 'paragon',
        ['Paragon2'] = 'paragon2',
        ['Pariah'] = 'pariah',
        ['Penumbra'] = 'penumbra',
        ['Penumbra2'] = 'penumbra2',
        ['Raiden'] = 'raiden',
        ['Rapidgt'] = 'rapidgt',
        ['Rapidgt2'] = 'rapidgt2',
        ['Raptor'] = 'raptor',
        ['Revolter'] = 'revolter',
        ['Ruston'] = 'ruston',
        ['Schafter2'] = 'schafter2',
        ['Schafter3'] = 'schafter3',
        ['Schafter4'] = 'schafter4',
        ['Schafter5'] = 'schafter5',
        ['Schafter6'] = 'schafter6',
        ['Schlagen'] = 'schlagen',
        ['Schwarzer'] = 'schwarzer',
        ['Sentinel3'] = 'sentinel3',
        ['Seven70'] = 'seven70',
        ['Specter'] = 'specter',
        ['Specter2'] = 'specter2',
        ['Streiter'] = 'streiter',
        ['Sugoi'] = 'sugoi',
        ['Sultan'] = 'sultan',
        ['Sultan2'] = 'sultan2',
        ['Surano'] = 'surano',
        ['Tampa2'] = 'tampa2',
        ['Tropos'] = 'tropos',
        ['Verlierer2'] = 'verlierer2',
        ['Vstr'] = 'vstr',
        ['Zr380'] = 'zr380',
        ['Zr3802'] = 'zr3802',
        ['Zr3803'] = 'zr3803',
        ['Italirsx'] = 'italirsx',
        ['Veto'] = 'veto',
        ['Veto2'] = 'veto2'
    },
    Super = {
        ['Adder'] = 'adder',
        ['Autarch'] = 'autarch',
        ['Banshee2'] = 'banshee2',
        ['Bullet'] = 'bullet',
        ['Cheetah'] = 'cheetah',
        ['Cyclone'] = 'cyclone',
        ['Entity2'] = 'entity2',
        ['Entityxf'] = 'entityxf',
        ['Emerus'] = 'emerus',
        ['Fmj'] = 'fmj',
        ['Furia'] = 'furia',
        ['Gp1'] = 'gp1',
        ['Infernus'] = 'infernus',
        ['Italigtb'] = 'italigtb',
        ['Italigtb2'] = 'italigtb2',
        ['Krieger'] = 'krieger',
        ['Le7b'] = 'le7b',
        ['Nero'] = 'nero',
        ['Nero2'] = 'nero2',
        ['Osiris'] = 'osiris',
        ['Penetrator'] = 'penetrator',
        ['Pfister811'] = 'pfister811',
        ['Prototipo'] = 'prototipo',
        ['Reaper'] = 'reaper',
        ['S80'] = 's80',
        ['Sc1'] = 'sc1',
        ['Scramjet'] = 'scramjet',
        ['Sheava'] = 'sheava',
        ['Sultanrs'] = 'sultanrs',
        ['T20'] = 't20',
        ['Taipan'] = 'taipan',
        ['Tempesta'] = 'tempesta',
        ['Tezeract'] = 'tezeract',
        ['Thrax'] = 'thrax',
        ['Tigon'] = 'tigon',
        ['Turismor'] = 'turismor',
        ['Tyrant'] = 'tyrant',
        ['Tyrus'] = 'tyrus',
        ['Vacca'] = 'vacca',
        ['Vagner'] = 'vagner',
        ['Vigilante'] = 'vigilante',
        ['Visione'] = 'visione',
        ['Voltic'] = 'voltic',
        ['Voltic2'] = 'voltic2',
        ['Xa21'] = 'xa21',
        ['Zentorno'] = 'zentorno',
        ['Zorrusso'] = 'zorrusso'
    },
    Motorcycles = {
        ['Akuma'] = 'akuma',
        ['Avarus'] = 'avarus',
        ['Bagger'] = 'bagger',
        ['Bati'] = 'bati',
        ['Bati2'] = 'bati2',
        ['Bf400'] = 'bf400',
        ['Carbonrs'] = 'carbonrs',
        ['Chimera'] = 'chimera',
        ['Cliffhanger'] = 'cliffhanger',
        ['Daemon'] = 'daemon',
        ['Daemon2'] = 'daemon2',
        ['Defiler'] = 'defiler',
        ['Deathbike'] = 'deathbike',
        ['Deathbike2'] = 'deathbike2',
        ['Deathbike3'] = 'deathbike3',
        ['Diablous'] = 'diablous',
        ['Diablous2'] = 'diablous2',
        ['Double'] = 'double',
        ['Enduro'] = 'enduro',
        ['Esskey'] = 'esskey',
        ['Faggio'] = 'faggio',
        ['Faggio2'] = 'faggio2',
        ['Faggio3'] = 'faggio3',
        ['Fcr'] = 'fcr',
        ['Fcr2'] = 'fcr2',
        ['Gargoyle'] = 'gargoyle',
        ['Hakuchou'] = 'hakuchou',
        ['Hakuchou2'] = 'hakuchou2',
        ['Hexer'] = 'hexer',
        ['Innovation'] = 'innovation',
        ['Lectro'] = 'lectro',
        ['Manchez'] = 'manchez',
        ['Nemesis'] = 'nemesis',
        ['Nightblade'] = 'nightblade',
        ['Oppressor'] = 'oppressor',
        ['Oppressor2'] = 'oppressor2',
        ['Pcj'] = 'pcj',
        ['Ratbike'] = 'ratbike',
        ['Ruffian'] = 'ruffian',
        ['Rrocket'] = 'rrocket',
        ['Sanchez'] = 'sanchez',
        ['Sanchez2'] = 'sanchez2',
        ['Sanctus'] = 'sanctus',
        ['Shotaro'] = 'shotaro',
        ['Sovereign'] = 'sovereign',
        ['Stryder'] = 'stryder',
        ['Thrust'] = 'thrust',
        ['Vader'] = 'vader',
        ['Vindicator'] = 'vindicator',
        ['Vortex'] = 'vortex',
        ['Wolfsbane'] = 'wolfsbane',
        ['Zombiea'] = 'zombiea',
        ['Zombieb'] = 'zombieb',
        ['Manchez2'] = 'manchez2'
    },
    OffRoad = {
        ['Bfinjection'] = 'bfinjection',
        ['Bifta'] = 'bifta',
        ['Blazer'] = 'blazer',
        ['Blazer2'] = 'blazer2',
        ['Blazer3'] = 'blazer3',
        ['Blazer4'] = 'blazer4',
        ['Blazer5'] = 'blazer5',
        ['Bodhi2'] = 'bodhi2',
        ['Brawler'] = 'brawler',
        ['Bruiser'] = 'bruiser',
        ['Bruiser2'] = 'bruiser2',
        ['Bruiser3'] = 'bruiser3',
        ['Brutus'] = 'brutus',
        ['Brutus2'] = 'brutus2',
        ['Brutus3'] = 'brutus3',
        ['Caracara'] = 'caracara',
        ['Caracara2'] = 'caracara2',
        ['Dloader'] = 'dloader',
        ['Dubsta3'] = 'dubsta3',
        ['Dune'] = 'dune',
        ['Dune2'] = 'dune2',
        ['Dune3'] = 'dune3',
        ['Dune4'] = 'dune4',
        ['Dune5'] = 'dune5',
        ['Everon'] = 'everon',
        ['Freecrawler'] = 'freecrawler',
        ['Hellion'] = 'hellion',
        ['Insurgent'] = 'insurgent',
        ['Insurgent2'] = 'insurgent2',
        ['Insurgent3'] = 'insurgent3',
        ['Kalahari'] = 'kalahari',
        ['Kamacho'] = 'kamacho',
        ['Marshall'] = 'marshall',
        ['Mesa3'] = 'mesa3',
        ['Monster'] = 'monster',
        ['Monster3'] = 'monster3',
        ['Monster4'] = 'monster4',
        ['Monster5'] = 'monster5',
        ['Menacer'] = 'menacer',
        ['Outlaw'] = 'outlaw',
        ['Nightshark'] = 'nightshark',
        ['Rancherxl'] = 'rancherxl',
        ['Rancherxl2'] = 'rancherxl2',
        ['Rebel'] = 'rebel',
        ['Rebel2'] = 'rebel2',
        ['Rcbandito'] = 'rcbandito',
        ['Riata'] = 'riata',
        ['Sandking'] = 'sandking',
        ['Sandking2'] = 'sandking2',
        ['Technical'] = 'technical',
        ['Technical2'] = 'technical2',
        ['Technical3'] = 'technical3',
        ['Trophytruck'] = 'trophytruck',
        ['Trophytruck2'] = 'trophytruck2',
        ['Vagrant'] = 'vagrant',
        ['Zhaba'] = 'zhaba',
        ['Verus'] = 'verus',
        ['Winky'] = 'winky'
    },
    Industrial = {
        ['Bulldozer'] = 'bulldozer',
        ['Cutter'] = 'cutter',
        ['Dump'] = 'dump',
        ['Flatbed'] = 'flatbed',
        ['Guardian'] = 'guardian',
        ['Handler'] = 'handler',
        ['Mixer'] = 'mixer',
        ['Mixer2'] = 'mixer2',
        ['Rubble'] = 'rubble',
        ['Tiptruck'] = 'tiptruck',
        ['Tiptruck2'] = 'tiptruck2'
    },
    Utility = {
        ['Airtug'] = 'airtug',
        ['Caddy'] = 'caddy',
        ['Caddy2'] = 'caddy2',
        ['Caddy3'] = 'caddy3',
        ['Docktug'] = 'docktug',
        ['Forklift'] = 'forklift',
        ['Mower'] = 'mower',
        ['Ripley'] = 'ripley',
        ['Sadler'] = 'sadler',
        ['Sadler2'] = 'sadler2',
        ['Scrap'] = 'scrap',
        ['Towtruck'] = 'towtruck',
        ['Towtruck2'] = 'towtruck2',
        ['Tractor'] = 'tractor',
        ['Tractor2'] = 'tractor2',
        ['Tractor3'] = 'tractor3',
        ['Utillitruck'] = 'utillitruck',
        ['Utillitruck2'] = 'utillitruck2',
        ['Utillitruck3'] = 'utillitruck3',
        ['Slamtruck'] = 'slamtruck'
    },
    Vans = {
        ['Bison'] = 'bison',
        ['Bison2'] = 'bison2',
        ['Bison3'] = 'bison3',
        ['Bobcatxl'] = 'bobcatxl',
        ['Boxville'] = 'boxville',
        ['Boxville2'] = 'boxville2',
        ['Boxville3'] = 'boxville3',
        ['Boxville4'] = 'boxville4',
        ['Boxville5'] = 'boxville5',
        ['Burrito'] = 'burrito',
        ['Burrito2'] = 'burrito2',
        ['Burrito3'] = 'burrito3',
        ['Burrito4'] = 'burrito4',
        ['Burrito5'] = 'burrito5',
        ['Camper'] = 'camper',
        ['Gburrito'] = 'gburrito',
        ['Gburrito2'] = 'gburrito2',
        ['Journey'] = 'journey',
        ['Minivan'] = 'minivan',
        ['Minivan2'] = 'minivan2',
        ['Paradise'] = 'paradise',
        ['Pony'] = 'pony',
        ['Pony2'] = 'pony2',
        ['Rumpo'] = 'rumpo',
        ['Rumpo2'] = 'rumpo2',
        ['Rumpo3'] = 'rumpo3',
        ['Speedo'] = 'speedo',
        ['Speedo2'] = 'speedo2',
        ['Speedo4'] = 'speedo4',
        ['Surfer'] = 'surfer',
        ['Surfer2'] = 'surfer2',
        ['Taco'] = 'taco',
        ['Youga'] = 'youga',
        ['Youga2'] = 'youga2',
        ['Youga3'] = 'youga3'        
    },
    Cycles = {
        ['Bmx'] = 'bmx',
        ['Cruiser'] = 'cruiser',
        ['Fixter'] = 'fixter',
        ['Scorcher'] = 'scorcher',
        ['Tribike'] = 'tribike',
        ['Tribike2'] = 'tribike2',
        ['Tribike3'] = 'tribike3'
    },
    Boats = {
        ['Dinghy'] = 'dinghy',
        ['Dinghy2'] = 'dinghy2',
        ['Dinghy3'] = 'dinghy3',
        ['Dinghy4'] = 'dinghy4',
        ['Jetmax'] = 'jetmax',
        ['Marquis'] = 'marquis',
        ['Seashark'] = 'seashark',
        ['Seashark2'] = 'seashark2',
        ['Seashark3'] = 'seashark3',
        ['Speeder'] = 'speeder',
        ['Speeder2'] = 'speeder2',
        ['Squalo'] = 'squalo',
        ['Submersible'] = 'submersible',
        ['Submersinle2'] = 'submersinle2',
        ['Suntrap'] = 'suntrap',
        ['Toro'] = 'toro',
        ['Toro2'] = 'toro2',
        ['Tropic'] = 'tropic',
        ['Tropic2'] = 'tropic2',
        ['Tug'] = 'tug',
        ['Avisa'] = 'avisa',
        ['Dinghy5'] = 'dinghy5',
        ['Kosatka'] = 'kosatka',
        ['Longfin'] = 'longfin',
        ['Patrolboat'] = 'patrolboat'        
    },
    Helicopters = {
        ['Akula'] = 'akula',
        ['Annihilator'] = 'annihilator',
        ['Buzzard'] = 'buzzard',
        ['Buzzard2'] = 'buzzard2',
        ['Cargobob'] = 'cargobob',
        ['Cargobob2'] = 'cargobob2',
        ['Cargobob3'] = 'cargobob3',
        ['Cargobob4'] = 'cargobob4',
        ['Frogger'] = 'frogger',
        ['Frogger2'] = 'frogger2',
        ['Havok'] = 'havok',
        ['Hunter'] = 'hunter',
        ['Maverick'] = 'maverick',
        ['Savage'] = 'savage',
        ['Seasparrow'] = 'seasparrow',
        ['Skylift'] = 'skylift',
        ['Supervolito'] = 'supervolito',
        ['Supervolito2'] = 'supervolito2',
        ['Swift'] = 'swift',
        ['Swift2'] = 'swift2',
        ['Valkyrie'] = 'valkyrie',
        ['Valkyrie2'] = 'valkyrie2',
        ['Volatus,'] = 'volatus,',
        ['Annihilator2'] = 'annihilator2',
        ['Seasparrow2'] = 'seasparrow2',
        ['Seasparrow3'] = 'seasparrow3'        
    },
    Planes = {
        ['Alphaz1'] = 'alphaz1',
        ['Avenger'] = 'avenger',
        ['Avenger2'] = 'avenger2',
        ['Besra'] = 'besra',
        ['Blimp2'] = 'blimp2',
        ['Blimp3'] = 'blimp3',
        ['Bombushka'] = 'bombushka',
        ['Cargoplane'] = 'cargoplane',
        ['Cuban800'] = 'cuban800',
        ['Dodo'] = 'dodo',
        ['Duster'] = 'duster',
        ['Howard'] = 'howard',
        ['Hydra'] = 'hydra',
        ['Jet'] = 'jet',
        ['Lazer'] = 'lazer',
        ['Luxor'] = 'luxor',
        ['Luxor2'] = 'luxor2',
        ['Mammatus'] = 'mammatus',
        ['Microlight'] = 'microlight',
        ['Miljet'] = 'miljet',
        ['Mogul'] = 'mogul',
        ['Molotok'] = 'molotok',
        ['Nimbus'] = 'nimbus',
        ['Nokota'] = 'nokota',
        ['Pyro'] = 'pyro',
        ['Rogue'] = 'rogue',
        ['Seabreeze'] = 'seabreeze',
        ['Shamal'] = 'shamal',
        ['Starling'] = 'starling',
        ['Strikeforce'] = 'strikeforce',
        ['Stunt'] = 'stunt',
        ['Titan'] = 'titan',
        ['Tula'] = 'tula',
        ['Velum'] = 'velum',
        ['Velum2'] = 'velum2',
        ['Vestra'] = 'vestra',
        ['Volatol'] = 'volatol',
        ['Alkonost'] = 'alkonost'
    },
    Service = {
        ['Airbus'] = 'airbus',
        ['Brickade'] = 'brickade',
        ['Bus'] = 'bus',
        ['Coach'] = 'coach',
        ['Pbus2'] = 'pbus2',
        ['Rallytruck'] = 'rallytruck',
        ['Rentalbus'] = 'rentalbus',
        ['Taxi'] = 'taxi',
        ['Tourbus'] = 'tourbus',
        ['Trash'] = 'trash',
        ['Trash2'] = 'trash2',
        ['Wastelander'] = 'wastelander'
    },
    Emergency = {
        ['Ambulance'] = 'ambulance',
        ['Fbi'] = 'fbi',
        ['Fbi2'] = 'fbi2',
        ['Firetruk'] = 'firetruk',
        ['Lguard'] = 'lguard',
        ['Pbus'] = 'pbus',
        ['Police'] = 'police',
        ['Police2'] = 'police2',
        ['Police3'] = 'police3',
        ['Police4'] = 'police4',
        ['Policeold2'] = 'policeold2',
        ['Policet'] = 'policet',
        ['Pranger'] = 'pranger',
        ['Predator'] = 'predator',
        ['Riot'] = 'riot',
        ['Riot2'] = 'riot2',
        ['Sheriff'] = 'sheriff',
        ['Sheriff2'] = 'sheriff2'
    },
    Military = {
        ['Apc'] = 'apc',
        ['Barracks'] = 'barracks',
        ['Barracks2'] = 'barracks2',
        ['Barracks3'] = 'barracks3',
        ['Barrage'] = 'barrage',
        ['Chernobog'] = 'chernobog',
        ['Crusader'] = 'crusader',
        ['Halftrack'] = 'halftrack',
        ['Khanjali'] = 'khanjali',
        ['Minitank'] = 'minitank',
        ['Rhino'] = 'rhino',
        ['Scarab'] = 'scarab',
        ['Scarab2'] = 'scarab2',
        ['Scarab3'] = 'scarab3',
        ['Thruster'] = 'thruster',
        ['Trailersmall2'] = 'trailersmall2',
        ['Vetir'] = 'vetir'
    },
    Commercial = {
        ['Benson'] = 'benson',
        ['Biff'] = 'biff',
        ['Cerberus'] = 'cerberus',
        ['Cerberus2'] = 'cerberus2',
        ['Cerberus3'] = 'cerberus3',
        ['Haulter'] = 'haulter',
        ['Haulter2'] = 'haulter2',
        ['Musclemule2'] = 'Musclemule2',
        ['Mule3'] = 'mule3',
        ['Mule4'] = 'mule4',
        ['Packer'] = 'packer',
        ['Phantom'] = 'phantom',
        ['Phantom2'] = 'phantom2',
        ['Phantom3'] = 'phantom3',
        ['Pounder'] = 'pounder',
        ['Pounder2'] = 'pounder2',
        ['Stockade'] = 'stockade',
        ['Stockade3'] = 'stockade3',
        ['Terbyte'] = 'terbyte'        
    },
    Trains = {
        ['Freight'] = 'freight',
        ['Freightcar'] = 'freightcar',
        ['Freightcont1'] = 'freightcont1',
        ['Freightcont2'] = 'freightcont2',
        ['Freightgrain'] = 'freightgrain',
        ['Metrotrain'] = 'metrotrain',
        ['Tankercar'] = 'tankercar'        
    },
    Open_Wheels = {
        ['Formula'] = 'formula',
        ['Formula2'] = 'formula2',
        ['Openwheel1'] = 'openwheel1',
        ['Openwheel2'] = 'openwheel2'        
    }
}

config.peds = {
        "ig_abigail",
        "csb_abigail",
        "u_m_y_abner",
        "a_m_m_acult_01",
        "a_m_o_acult_01",
        "a_m_y_acult_01",
        "a_m_o_acult_02",
        "a_m_y_acult_02",
        "a_m_m_afriamer_01",
        "ig_mp_agent14",
        "csb_mp_agent14",
        "csb_agent",
        "s_f_y_airhostess_01",
        "s_m_y_airworker",
        "u_m_m_aldinapoli",
        "ig_amandatownley",
        "cs_amandatownley",
        "s_m_y_ammucity_01",
        "s_m_m_ammucountry",
        "ig_andreas",
        "cs_andreas",
        "csb_anita",
        "u_m_y_antonb",
        "csb_anton",
        "g_m_m_armboss_01",
        "g_m_m_armgoon_01",
        "g_m_y_armgoon_02",
        "g_m_m_armlieut_01",
        "mp_s_m_armoured_01",
        "s_m_m_armoured_01",
        "s_m_m_armoured_02",
        "s_m_y_armymech_01",
        "ig_ashley",
        "cs_ashley",
        "s_m_y_autopsy_01",
        "s_m_m_autoshop_01",
        "s_m_m_autoshop_02",
        "ig_money",
        "csb_money",
        "g_m_y_azteca_01",
        "u_m_y_babyd",
        "g_m_y_ballaeast_01",
        "g_m_y_ballaorig_01",
        "g_f_y_ballas_01",
        "ig_ballasog",
        "csb_ballasog",
        "g_m_y_ballasout_01",
        "u_m_m_bankman",
        "ig_bankman",
        "cs_bankman",
        "s_m_y_barman_01",
        "ig_barry",
        "cs_barry",
        "s_f_y_bartender_01",
        "u_m_y_baygor",
        "s_f_y_baywatch_01",
        "s_m_y_baywatch_01",
        "a_f_m_beach_01",
        "a_f_y_beach_01",
        "a_m_m_beach_01",
        "a_m_o_beach_01",
        "a_m_y_beach_01",
        "a_m_m_beach_02",
        "a_m_y_beach_02",
        "a_m_y_beach_03",
        "a_m_y_beachvesp_01",
        "a_m_y_beachvesp_02",
        "ig_benny",
        "ig_bestmen",
        "ig_beverly",
        "cs_beverly",
        "a_f_m_bevhills_01",
        "a_f_y_bevhills_01",
        "a_m_m_bevhills_01",
        "a_m_y_bevhills_01",
        "a_f_m_bevhills_02",
        "a_f_y_bevhills_02",
        "a_m_m_bevhills_02",
        "a_m_y_bevhills_02",
        "a_f_y_bevhills_03",
        "a_f_y_bevhills_04",
        "u_m_m_bikehire_01",
        "u_f_y_bikerchic",
        "s_m_y_blackops_01",
        "s_m_y_blackops_02",
        "s_m_y_blackops_03",
        "a_c_boar",
        "mp_f_boatstaff_01",
        "mp_m_boatstaff_01",
        "a_f_m_bodybuild_01",
        "s_m_m_bouncer_01",
        "ig_brad",
        "cs_bradcadaver",
        "cs_brad",
        "a_m_y_breakdance_01",
        "ig_bride",
        "csb_bride",
        "u_m_y_burgerdrug_01",
        "csb_burgerdrug",
        "s_m_y_busboy_01",
        "a_m_y_busicas_01",
        "a_f_y_business_01",
        "a_m_m_business_01",
        "a_m_y_business_01",
        "a_f_m_business_02",
        "a_f_y_business_02",
        "a_m_y_business_02",
        "a_f_y_business_03",
        "a_m_y_business_03",
        "a_f_y_business_04",
        "s_m_o_busker_01",
        "ig_car3guy1",
        "csb_car3guy1",
        "ig_car3guy2",
        "csb_car3guy2",
        "cs_carbuyer",
        "ig_casey",
        "cs_casey",
        "a_c_cat_01",
        "s_m_m_ccrew_01",
        "s_m_y_chef_01",
        "ig_chef2",
        "csb_chef2",
        "ig_chef",
        "csb_chef",
        "s_m_m_chemsec_01",
        "g_m_m_chemwork_01",
        "g_m_m_chiboss_01",
        "a_c_chickenhawk",
        "g_m_m_chicold_01",
        "g_m_m_chigoon_01",
        "g_m_m_chigoon_02",
        "a_c_chimp",
        "csb_chin_goon",
        "u_m_y_chip",
        "a_c_chop",
        "s_m_m_ciasec_01",
        "mp_m_claude_01",
        "ig_clay",
        "cs_clay",
        "ig_claypain",
        "ig_cletus",
        "csb_cletus",
        "s_m_y_clown_01",
        "s_m_m_cntrybar_01",
        "u_f_y_comjane",
        "s_m_y_construct_01",
        "s_m_y_construct_02",
        "s_f_y_cop_01",
        "s_m_y_cop_01",
        "csb_cop",
        "a_c_cormorant",
        "u_f_m_corpse_01",
        "u_f_y_corpse_02",
        "a_c_cow",
        "a_c_coyote",
        "ig_chrisformage",
        "cs_chrisformage",
        "a_c_crow",
        "csb_customer",
        "u_m_y_cyclist_01",
        "a_m_y_cyclist_01",
        "ig_dale",
        "cs_dale",
        "ig_davenorton",
        "cs_davenorton",
        "s_m_y_dealer_01",
        "cs_debra",
        "a_c_deer",
        "ig_denise",
        "cs_denise",
        "csb_denise_friend",
        "ig_devin",
        "cs_devin",
        "s_m_y_devinsec_01",
        "a_m_y_dhill_01",
        "u_m_m_doa_01",
        "s_m_m_dockwork_01",
        "s_m_y_dockwork_01",
        "s_m_m_doctor_01",
        "a_c_dolphin",
        "ig_dom",
        "cs_dom",
        "s_m_y_doorman_01",
        "a_f_m_downtown_01",
        "a_m_y_downtown_01",
        "ig_dreyfuss",
        "cs_dreyfuss",
        "ig_drfriedlander",
        "cs_drfriedlander",
        "mp_f_deadhooker",
        "s_m_y_dwservice_01",
        "s_m_y_dwservice_02",
        "a_f_m_eastsa_01",
        "a_f_y_eastsa_01",
        "a_m_m_eastsa_01",
        "a_m_y_eastsa_01",
        "a_f_m_eastsa_02",
        "a_f_y_eastsa_02",
        "a_m_m_eastsa_02",
        "a_m_y_eastsa_02",
        "a_f_y_eastsa_03",
        "u_m_m_edtoh",
        "a_f_y_epsilon_01",
        "a_m_y_epsilon_01",
        "a_m_y_epsilon_02",
        "mp_m_exarmy_01",
        "ig_fabien",
        "cs_fabien",
        "s_f_y_factory_01",
        "s_m_y_factory_01",
        "g_m_y_famca_01",
        "mp_m_famdd_01",
        "g_m_y_famdnf_01",
        "g_m_y_famfor_01",
        "g_f_y_families_01",
        "a_m_m_farmer_01",
        "a_f_m_fatbla_01",
        "a_f_m_fatcult_01",
        "a_m_m_fatlatin_01",
        "a_f_m_fatwhite_01",
        "ig_fbisuit_01",
        "cs_fbisuit_01",
        "s_f_m_fembarber",
        "u_m_m_fibarchitect",
        "u_m_y_fibmugger_01",
        "s_m_m_fiboffice_01",
        "s_m_m_fiboffice_02",
        "mp_m_fibsec_01",
        "s_m_m_fibsec_01",
        "u_m_m_filmdirector",
        "u_m_o_filmnoir",
        "u_m_o_finguru_01",
        "s_m_y_fireman_01",
        "a_c_fish",
        "a_f_y_fitness_01",
        "a_f_y_fitness_02",
        "ig_floyd",
        "cs_floyd",
        "csb_fos_rep",
        "player_one",
        "mp_f_freemode_01",
        "mp_m_freemode_01",
        "ig_g",
        "s_m_m_gaffer_01",
        "s_m_y_garbage",
        "s_m_m_gardener_01",
        "a_m_y_gay_01",
        "a_m_y_gay_02",
        "csb_g",
        "a_m_m_genfat_01",
        "a_m_m_genfat_02",
        "a_f_y_genhot_01",
        "a_f_o_genstreet_01",
        "a_m_o_genstreet_01",
        "a_m_y_genstreet_01",
        "a_m_y_genstreet_02",
        "s_m_m_gentransport",
        "u_m_m_glenstank_01",
        "a_f_y_golfer_01",
        "a_m_m_golfer_01",
        "a_m_y_golfer_01",
        "u_m_m_griff_01",
        "s_m_y_grip_01",
        "ig_groom",
        "csb_groom",
        "csb_grove_str_dlr",
        "cs_guadalope",
        "u_m_y_guido_01",
        "u_m_y_gunvend_01",
        "cs_gurk",
        "hc_hacker",
        "s_m_m_hairdress_01",
        "a_c_sharkhammer",
        "ig_hao",
        "csb_hao",
        "a_m_m_hasjew_01",
        "a_m_y_hasjew_01",
        "a_c_hen",
        "s_m_m_highsec_01",
        "s_m_m_highsec_02",
        "a_f_y_hiker_01",
        "a_m_y_hiker_01",
        "a_m_m_hillbilly_01",
        "a_m_m_hillbilly_02",
        "u_m_y_hippie_01",
        "a_f_y_hippie_01",
        "a_m_y_hippy_01",
        "a_f_y_hipster_01",
        "a_m_y_hipster_01",
        "a_f_y_hipster_02",
        "a_m_y_hipster_02",
        "a_f_y_hipster_03",
        "a_m_y_hipster_03",
        "a_f_y_hipster_04",
        "s_f_y_hooker_01",
        "s_f_y_hooker_02",
        "s_f_y_hooker_03",
        "u_f_y_hotposh_01",
        "csb_hugh",
        "a_c_humpback",
        "ig_hunter",
        "cs_hunter",
        "a_c_husky",
        "s_m_y_hwaycop_01",
        "u_m_y_imporage",
        "csb_imran",
        "a_f_o_indian_01",
        "a_f_y_indian_01",
        "a_m_m_indian_01",
        "a_m_y_indian_01",
        "csb_jackhowitzer",
        "ig_janet",
        "cs_janet",
        "csb_janitor",
        "s_m_m_janitor",
        "ig_jay_norris",
        "u_m_m_jesus_01",
        "a_m_y_jetski_01",
        "u_f_y_jewelass_01",
        "ig_jewelass",
        "cs_jewelass",
        "u_m_m_jewelsec_01",
        "u_m_m_jewelthief",
        "ig_jimmyboston",
        "cs_jimmyboston",
        "ig_jimmydisanto",
        "cs_jimmydisanto",
        "ig_joeminuteman",
        "cs_joeminuteman",
        "ig_johnnyklebitz",
        "cs_johnnyklebitz",
        "ig_josef",
        "cs_josef",
        "ig_josh",
        "cs_josh",
        "a_f_y_juggalo_01",
        "a_m_y_juggalo_01",
        "u_m_y_justin",
        "ig_karen_daniels",
        "cs_karen_daniels",
        "ig_kerrymcintosh",
        "a_c_killerwhale",
        "g_m_m_korboss_01",
        "g_m_y_korean_01",
        "g_m_y_korean_02",
        "g_m_y_korlieut_01",
        "a_f_m_ktown_01",
        "a_f_o_ktown_01",
        "a_m_m_ktown_01",
        "a_m_o_ktown_01",
        "a_m_y_ktown_01",
        "a_f_m_ktown_02",
        "a_m_y_ktown_02",
        "ig_lamardavis",
        "cs_lamardavis",
        "s_m_m_lathandy_01",
        "a_m_y_latino_01",
        "ig_lazlow",
        "cs_lazlow",
        "ig_lestercrest",
        "cs_lestercrest",
        "ig_lifeinvad_01",
        "cs_lifeinvad_01",
        "s_m_m_lifeinvad_01",
        "ig_lifeinvad_02",
        "s_m_m_linecook",
        "g_f_y_lost_01",
        "g_m_y_lost_01",
        "g_m_y_lost_02",
        "g_m_y_lost_03",
        "s_m_m_lsmetro_01",
        "ig_magenta",
        "cs_magenta",
        "s_f_m_maid_01",
        "a_m_m_malibu_01",
        "u_m_y_mani",
        "ig_manuel",
        "cs_manuel",
        "s_m_m_mariachi_01",
        "s_m_m_marine_01",
        "s_m_y_marine_01",
        "s_m_m_marine_02",
        "s_m_y_marine_02",
        "s_m_y_marine_03",
        "u_m_m_markfost",
        "ig_marnie",
        "cs_marnie",
        "mp_m_marston_01",
        "cs_martinmadrazo",
        "ig_maryann",
        "cs_maryann",
        "ig_maude",
        "csb_maude",
        "csb_mweather",
        "a_m_y_methhead_01",
        "g_m_m_mexboss_01",
        "g_m_m_mexboss_02",
        "a_m_m_mexcntry_01",
        "g_m_y_mexgang_01",
        "g_m_y_mexgoon_01",
        "g_m_y_mexgoon_02",
        "g_m_y_mexgoon_03",
        "a_m_m_mexlabor_01",
        "a_m_y_mexthug_01",
        "player_zero",
        "ig_michelle",
        "cs_michelle",
        "s_f_y_migrant_01",
        "s_m_m_migrant_01",
        "u_m_y_militarybum",
        "ig_milton",
        "cs_milton",
        "s_m_y_mime",
        "u_f_m_miranda",
        "u_f_y_mistress",
        "mp_f_misty_01",
        "ig_molly",
        "cs_molly",
        "a_m_y_motox_01",
        "a_m_y_motox_02",
        "a_c_mtlion",
        "s_m_m_movalien_01",
        "cs_movpremf_01",
        "cs_movpremmale",
        "u_f_o_moviestar",
        "s_f_y_movprem_01",
        "s_m_m_movprem_01",
        "s_m_m_movspace_01",
        "mp_g_m_pros_01",
        "ig_mrk",
        "cs_mrk",
        "ig_mrsphillips",
        "cs_mrsphillips",
        "ig_mrs_thornhill",
        "cs_mrs_thornhill",
        "a_m_y_musclbeac_01",
        "a_m_y_musclbeac_02",
        "ig_natalia",
        "cs_natalia",
        "ig_nervousron",
        "cs_nervousron",
        "ig_nigel",
        "cs_nigel",
        "mp_m_niko_01",
        "a_m_m_og_boss_01",
        "ig_old_man1a",
        "cs_old_man1a",
        "ig_old_man2",
        "cs_old_man2",
        "ig_omega",
        "cs_omega",
        "ig_oneil",
        "ig_orleans",
        "cs_orleans",
        "ig_ortega",
        "csb_ortega",
        "csb_oscar",
        "ig_paige",
        "csb_paige",
        "a_m_m_paparazzi_01",
        "u_m_y_paparazzi",
        "ig_paper",
        "cs_paper",
        "s_m_m_paramedic_01",
        "u_m_y_party_01",
        "u_m_m_partytarget",
        "ig_patricia",
        "cs_patricia",
        "s_m_y_pestcont_01",
        "hc_driver",
        "hc_gunman",
        "a_c_pig",
        "a_c_pigeon",
        "s_m_m_pilot_01",
        "s_m_y_pilot_01",
        "s_m_m_pilot_02",
        "u_m_y_pogo_01",
        "g_m_y_pologoon_01",
        "g_m_y_pologoon_02",
        "a_m_m_polynesian_01",
        "a_m_y_polynesian_01",
        "a_c_poodle",
        "ig_popov",
        "csb_popov",
        "u_f_y_poppymich",
        "csb_porndudes",
        "s_m_m_postal_01",
        "s_m_m_postal_02",
        "ig_priest",
        "cs_priest",
        "u_f_y_princess",
        "s_m_m_prisguard_01",
        "s_m_y_prismuscl_01",
        "u_m_y_prisoner_01",
        "s_m_y_prisoner_01",
        "u_m_y_proldriver_01",
        "csb_prologuedriver",
        "u_f_o_prolhost_01",
        "a_f_m_prolhost_01",
        "a_m_m_prolhost_01",
        "u_f_m_promourn_01",
        "u_m_m_promourn_01",
        "u_m_m_prolsec_01",
        "csb_prolsec",
        "ig_prolsec_02",
        "cs_prolsec_02",
        "a_c_pug",
        "a_c_rabbit_01",
        "ig_ramp_gang",
        "csb_ramp_gang",
        "ig_ramp_hic",
        "csb_ramp_hic",
        "ig_ramp_hipster",
        "csb_ramp_hipster",
        "csb_ramp_marine",
        "ig_ramp_mex",
        "csb_ramp_mex",
        "s_f_y_ranger_01",
        "s_m_y_ranger_01",
        "ig_rashcosvki",
        "csb_rashcosvki",
        "a_c_rat",
        "csb_reporter",
        "a_c_retriever",
        "a_c_rhesus",
        "u_m_m_rivalpap",
        "a_m_y_roadcyc_01",
        "s_m_y_robber_01",
        "ig_roccopelosi",
        "csb_roccopelosi",
        "a_c_rottweiler",
        "u_m_y_rsranger_01",
        "a_f_y_runner_01",
        "a_m_y_runner_01",
        "a_m_y_runner_02",
        "a_f_y_rurmeth_01",
        "a_m_m_rurmeth_01",
        "ig_russiandrunk",
        "cs_russiandrunk",
        "a_f_m_salton_01",
        "a_f_o_salton_01",
        "a_m_m_salton_01",
        "a_m_o_salton_01",
        "a_m_y_salton_01",
        "a_m_m_salton_02",
        "a_m_m_salton_03",
        "a_m_m_salton_04",
        "g_m_y_salvaboss_01",
        "g_m_y_salvagoon_01",
        "g_m_y_salvagoon_02",
        "g_m_y_salvagoon_03",
        "u_m_y_sbike",
        "a_f_y_scdressy_01",
        "s_m_m_scientist_01",
        "ig_screen_writer",
        "csb_screen_writer",
        "s_f_y_scrubs_01",
        "a_c_seagull",
        "s_m_m_security_01",
        "a_c_shepherd",
        "s_f_y_sheriff_01",
        "s_m_y_sheriff_01",
        "s_f_m_shop_high",
        "mp_m_shopkeep_01",
        "s_f_y_shop_low",
        "s_m_y_shop_mask",
        "s_f_y_shop_mid",
        "ig_siemonyetarian",
        "cs_siemonyetarian",
        "a_f_y_skater_01",
        "a_m_m_skater_01",
        "a_m_y_skater_01",
        "a_m_y_skater_02",
        "a_f_m_skidrow_01",
        "a_m_m_skidrow_01",
        "s_m_m_snowcop_01",
        "a_m_m_socenlat_01",
        "ig_solomon",
        "cs_solomon",
        "a_f_m_soucent_01",
        "a_f_o_soucent_01",
        "a_f_y_soucent_01",
        "a_m_m_soucent_01",
        "a_m_o_soucent_01",
        "a_m_y_soucent_01",
        "a_f_m_soucent_02",
        "a_f_o_soucent_02",
        "a_f_y_soucent_02",
        "a_m_m_soucent_02",
        "a_m_o_soucent_02",
        "a_m_y_soucent_02",
        "a_f_y_soucent_03",
        "a_m_m_soucent_03",
        "a_m_o_soucent_03",
        "a_m_y_soucent_03",
        "a_m_m_soucent_04",
        "a_m_y_soucent_04",
        "a_f_m_soucentmc_01",
        "u_m_m_spyactor",
        "u_f_y_spyactress",
        "u_m_y_staggrm_01",
        "a_m_y_stbla_01",
        "a_m_y_stbla_02",
        "ig_stevehains",
        "cs_stevehains",
        "a_c_stingray",
        "a_m_y_stlat_01",
        "a_m_m_stlat_02",
        "ig_stretch",
        "cs_stretch",
        "csb_stripper_01",
        "s_f_y_stripper_01",
        "csb_stripper_02",
        "s_f_y_stripper_02",
        "mp_f_stripperlite",
        "s_f_y_stripperlite",
        "s_m_m_strperf_01",
        "s_m_m_strpreach_01",
        "g_m_y_strpunk_01",
        "g_m_y_strpunk_02",
        "s_m_m_strvend_01",
        "s_m_y_strvend_01",
        "a_m_y_stwhi_01",
        "a_m_y_stwhi_02",
        "a_m_y_sunbathe_01",
        "a_m_y_surfer_01",
        "s_m_y_swat_01",
        "s_f_m_sweatshop_01",
        "s_f_y_sweatshop_01",
        "ig_talina",
        "ig_tanisha",
        "cs_tanisha",
        "ig_taocheng",
        "cs_taocheng",
        "ig_taostranslator",
        "cs_taostranslator",
        "u_m_o_taphillbilly",
        "u_m_y_tattoo_01",
        "a_f_y_tennis_01",
        "a_m_m_tennis_01",
        "ig_tenniscoach",
        "cs_tenniscoach",
        "ig_terry",
        "cs_terry",
        "a_c_sharktiger",
        "cs_tom",
        "ig_tomepsilon",
        "cs_tomepsilon",
        "ig_tonya",
        "csb_tonya",
        "a_f_y_topless_01",
        "a_f_m_tourist_01",
        "a_f_y_tourist_01",
        "a_m_m_tourist_01",
        "a_f_y_tourist_02",
        "ig_tracydisanto",
        "cs_tracydisanto",
        "ig_trafficwarden",
        "csb_trafficwarden",
        "u_m_o_tramp_01",
        "a_f_m_tramp_01",
        "a_m_m_tramp_01",
        "a_m_o_tramp_01",
        "a_f_m_trampbeac_01",
        "a_m_m_trampbeac_01",
        "a_m_m_tranvest_01",
        "a_m_m_tranvest_02",
        "player_two",
        "s_m_m_trucker_01",
        "ig_tylerdix",
        "csb_undercover",
        "s_m_m_ups_01",
        "s_m_m_ups_02",
        "s_m_y_uscg_01",
        "g_f_y_vagos_01",
        "mp_m_g_vagfun_01",
        "ig_vagspeak",
        "csb_vagspeak",
        "s_m_y_valet_01",
        "a_m_y_vindouche_01",
        "a_f_y_vinewood_01",
        "a_m_y_vinewood_01",
        "a_f_y_vinewood_02",
        "a_m_y_vinewood_02",
        "a_f_y_vinewood_03",
        "a_m_y_vinewood_03",
        "a_f_y_vinewood_04",
        "a_m_y_vinewood_04",
        "ig_wade",
        "cs_wade",
        "s_m_y_waiter_01",
        "ig_chengsr",
        "cs_chengsr",
        "a_c_westy",
        "u_m_m_willyfist",
        "s_m_y_winclean_01",
        "s_m_y_xmech_01",
        "s_m_y_xmech_02",
        "a_f_y_yoga_01",
        "a_m_y_yoga_01",
        "ig_zimbor",
        "cs_zimbor",
        "u_m_y_zombie_01",
        "a_f_y_femaleagent",
        "g_f_importexport_01",
        "g_m_importexport_01",
        "ig_agent",
        "ig_malc",
        "mp_f_cardesign_01",
        "mp_f_chbar_01",
        "mp_f_cocaine_01",
        "mp_f_counterfeit_01",
        "mp_f_execpa_01",
        "mp_f_execpa_02",
        "mp_f_forgery_01",
        "mp_f_helistaff_01",
        "mp_f_meth_01",
        "mp_f_weed_01",
        "mp_m_cocaine_01",
        "mp_m_counterfeit_01",
        "mp_m_execpa_01",
        "mp_m_forgery_01",
        "mp_m_meth_01",
        "mp_m_securoguard_01",
        "mp_m_waremech_01",
        "mp_m_weapexp_01",
        "mp_m_weapwork_01",
        "mp_m_weed_01",
        "s_m_y_xmech_02_mp",
        "u_f_m_drowned_01",
        "u_f_y_corpse_01",
        "u_m_m_streetart_01",
        "ig_lestercrest_2",
        "ig_avon",
        "u_m_y_juggernaut_01",
        "mp_m_avongoon",
        "mp_m_bogdangoon",
        "u_m_y_corpse_01",
        "a_c_panther",
        "a_f_y_beach_02",
        "a_f_y_clubcust_04",
        "a_m_o_beach_02",
        "a_m_y_beach_04",
        "a_m_y_clubcust_04",
        "cs_patricia_02",
        "csb_ary",
        "csb_englishdave_02",
        "csb_gustavo",
        "csb_helmsmanpavel",
        "csb_isldj_00",
        "csb_isldj_01",
        "csb_iSLdj_02",
        "csb_isldj_03",
        "csb_isldj_04",
        "csb_jio",
        "csb_juanstrickler",
        "csb_miguelmadrazo",
        "csb_mjo",
        "csb_sss",
        "g_m_m_cartelguards_01",
        "g_m_m_cartelguards_02",
        "ig_ary",
        "ig_englishdave_02",
        "ig_gustavo",
        "ig_helmsmanpavel",
        "ig_isldj_00",
        "ig_isldj_01",
        "ig_isldj_02",
        "ig_isldj_03",
        "ig_isldj_04",
        "ig_isldj_04_d_01",
        "ig_isldj_04_d_02",
        "ig_isldj_04_e_01",
        "ig_jackie",
        "ig_jio",
        "ig_juanstrickler",
        "ig_kaylee",
        "ig_miguelmadrazo",
        "ig_mjo",
        "ig_oldrichguy",
        "ig_patricia_02",
        "ig_pilot",
        "ig_sss",
        "s_f_y_beachbarstaff_01",
        "s_f_y_clubbar_02",
        "s_m_m_bouncer_02",
        "s_m_m_drugprocess_01",
        "s_m_m_fieldworker_01",
        "s_m_m_highsec_04"
}
